version: '3'
services:
  ts:
    build: .
    container_name: ts
    ports:
      - 8080:8080
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    # command: npm install  # Use FirstTime
    # command: npm run dev